import Link from "next/link";
import InstallSkipsDemoNav from "@/components/InstallSkipsDemoNav";

const contents = [
  "Mixed general waste",
  "Timber",
  "Small amount of rubble",
  "Packaging",
];

const checks = [
  "No asbestos declared",
  "No gas bottles",
  "No paint tins",
  "No plasterboard",
  "No fridges / freezers",
  "No tyres",
  "No chemicals",
];

export default function SkipTicketPage() {
  return (
    <main className="min-h-screen bg-[#070b08] text-white">
      <InstallSkipsDemoNav />

      <section className="mx-auto max-w-[1600px] px-4 py-8 sm:px-6 lg:px-8">
        <div className="rounded-[2rem] border border-white/10 bg-white/[0.05] p-6">
          <p className="text-sm font-black uppercase tracking-[0.28em] text-emerald-300">Digital Waste Ticket</p>
          <h1 className="mt-2 text-4xl font-black">Skip Ticket WTN-2026-0048</h1>
          <p className="mt-3 text-sm leading-6 text-slate-300">
            Contents, contamination checks, collection photos, driver note, customer signature and yard copy.
          </p>
        </div>

        <section className="mt-6 grid gap-5 lg:grid-cols-[1fr_0.8fr]">
          <article className="rounded-[2rem] border border-white/10 bg-white/[0.04] p-5">
            <div className="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between">
              <div>
                <h2 className="text-2xl font-black">Job Details</h2>
                <p className="mt-1 text-sm text-slate-400">Generated by TradeConnectAI demo</p>
              </div>
              <span className="w-fit rounded-full bg-emerald-400/15 px-4 py-2 text-xs font-black text-emerald-200">
                SIGNED - READY FOR YARD
              </span>
            </div>

            <div className="mt-5 grid gap-3 sm:grid-cols-2">
              {[
                ["Ticket", "WTN-2026-0048"],
                ["Job", "JOB-1882"],
                ["Customer", "A. Jenkins"],
                ["Site Address", "22 Redbrink Crescent, Barry, CF62"],
                ["Skip", "SKIP-014"],
                ["Size", "8 Yard"],
                ["Driver", "Dean Horgan"],
                ["Disposal Site", "South Wales Transfer Yard"],
                ["Dropped", "08:42"],
                ["Collected", "15:25"],
                ["Load", "Estimated 85% full"],
                ["Permit", "Not required - private driveway"],
              ].map(([label, value]) => (
                <div key={label} className="rounded-2xl border border-white/10 bg-black/25 p-4">
                  <p className="text-xs font-bold uppercase tracking-widest text-slate-500">{label}</p>
                  <p className="mt-2 text-sm font-black text-white">{value}</p>
                </div>
              ))}
            </div>

            <div className="mt-5 rounded-3xl border border-emerald-300/20 bg-emerald-400/10 p-5">
              <h3 className="text-lg font-black">AI Paperwork Note</h3>
              <p className="mt-2 text-sm leading-6 text-slate-200">
                Customer confirmed contents by web form before collection. No restricted items declared.
                Digital ticket generated and ready for customer, driver and yard copy.
              </p>
            </div>
          </article>

          <aside className="space-y-5">
            <div className="rounded-[2rem] border border-white/10 bg-white/[0.04] p-5">
              <h2 className="text-2xl font-black">Waste Contents</h2>
              <div className="mt-4 space-y-3">
                {contents.map((item) => (
                  <div key={item} className="rounded-2xl bg-black/25 p-3 text-sm font-bold text-slate-200">✅ {item}</div>
                ))}
              </div>
            </div>

            <div className="rounded-[2rem] border border-white/10 bg-white/[0.04] p-5">
              <h2 className="text-2xl font-black">Contamination Check</h2>
              <div className="mt-4 space-y-3">
                {checks.map((item) => (
                  <div key={item} className="rounded-2xl bg-black/25 p-3 text-sm font-bold text-slate-200">✅ {item}</div>
                ))}
              </div>
            </div>
          </aside>
        </section>

        <section className="mt-6 grid gap-5 lg:grid-cols-3">
          {[
            ["Drop-off Photo", "Captured 08:42", "Private driveway, access clear"],
            ["Collection Photo", "Captured 15:25", "Load photographed before lift"],
            ["Yard Copy", "Sent 15:31", "Ticket queued for transfer station"],
          ].map(([title, time, note]) => (
            <div key={title} className="rounded-[2rem] border border-white/10 bg-white/[0.04] p-5">
              <div className="flex h-40 items-center justify-center rounded-3xl border border-white/10 bg-gradient-to-br from-emerald-400/20 to-black/20 text-5xl">
                📷
              </div>
              <h3 className="mt-4 text-xl font-black">{title}</h3>
              <p className="mt-1 text-sm font-bold text-emerald-300">{time}</p>
              <p className="mt-2 text-sm text-slate-300">{note}</p>
            </div>
          ))}
        </section>

        <section className="mt-6 rounded-[2rem] border border-white/10 bg-white/[0.04] p-5">
          <h2 className="text-2xl font-black">Signatures</h2>
          <div className="mt-4 grid gap-4 md:grid-cols-2">
            <div className="rounded-3xl border border-white/10 bg-black/25 p-5">
              <p className="text-sm font-bold text-slate-400">Customer Signature</p>
              <div className="mt-5 rounded-2xl bg-white p-5 text-3xl font-black italic text-black">A. Jenkins</div>
              <p className="mt-3 text-xs font-bold text-emerald-300">Signed 15:27</p>
            </div>
            <div className="rounded-3xl border border-white/10 bg-black/25 p-5">
              <p className="text-sm font-bold text-slate-400">Driver Signature</p>
              <div className="mt-5 rounded-2xl bg-white p-5 text-3xl font-black italic text-black">Dean Horgan</div>
              <p className="mt-3 text-xs font-bold text-emerald-300">Signed 15:28</p>
            </div>
          </div>
        </section>

        <section className="mt-6 flex flex-wrap gap-3 rounded-[2rem] border border-white/10 bg-black/30 p-5">
          {[
            "Add Contents",
            "Flag Contamination",
            "Send Ticket to Customer",
            "Send Ticket to Yard",
            "Upload Drop-off Photo",
            "Upload Collection Photo",
            "Customer Signature",
            "Driver Signature",
          ].map((button) => (
            <Link key={button} href="/install-skips-demo/operations" className="rounded-2xl border border-white/15 px-4 py-3 text-sm font-black text-white hover:bg-white/10">
              {button}
            </Link>
          ))}
        </section>
      </section>
    </main>
  );
}

